src/librehatti/suspense/urls.py
# -*- coding: utf-8 -*-
from django.urls import re_path

from . import views


urlpatterns = [
    re_path(r"^add_distance", views.add_distance, name="add_distance"),
    re_path(r"^clresult/", views.clearance_result, name="clearance_result"),
    re_path(r"^clsearch/", views.clearance_search, name="clearance_search"),
    re_path(r"^othercharges/", views.other_charges, name="other_charges"),
    re_path(r"^tada_result/", views.tada_result, name="tada_result"),
    re_path(
        r"^tada_order_session/",
        views.tada_order_session,
        name="tada_order_session",
    ),
    re_path(r"^with_transport/", views.with_transport, name="with_transport"),
    re_path(r"^transport/", views.transport, name="transport"),
    re_path(r"^transportbill/", views.transportbill, name="transportbill"),
    re_path(
        r"^quoted_add_distance",
        views.quoted_add_distance,
        name="quoted_add_distance",
    ),
    re_path(
        r"^quoted_save_distance",
        views.quoted_save_distance,
        name="quoted_save_distance",
    ),
    re_path(r"^save_distance", views.save_distance, name="save_distance"),
    re_path(r"^sessionselect/", views.sessionselect, name="sessionselect"),
    re_path(r"^mark_clear/", views.mark_clear, name="mark_clear"),
    re_path(r"^mark_status/", views.mark_status, name="mark_status"),
    re_path(
        r"^clearance_options/",
        views.clearance_options,
        name="clearance_options",
    ),
    re_path(r"^summary_page/", views.summary_page, name="summary_page"),
    re_path(r"^transport_bill/", views.transport_bill, name="transport_bill"),
    re_path(r"^tada_bill/", views.tada_bill, name="tada_bill"),
    re_path(r"^tada_bill_list/", views.tada_bill_list, name="tada_bill_list"),
    re_path(
        r"^car_taxi_advance_form/",
        views.car_taxi_advance_form,
        name="car_taxi_advance_form",
    ),
    re_path(
        r"^car_taxi_advance/", views.car_taxi_advance, name="car_taxi_advance"
    ),
]

src/librehatti/urls.py
# -*- coding: utf-8 -*-
# from django.urls import patterns, include, url
from ajax_select import urls as ajax_select_urls
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path

from .catalog import views as catalog_views
from .prints import views as prints_views
from .programmeletter import views as programmeletter_views
from .reports import previous_history, register, views as reports_views
from .reports.register_generator import GenerateRegister
from .reports.search import SearchResult


admin.autodiscover()
urlpatterns = [
    path("api/auth/", include("djoser.urls.authtoken")),
    re_path(r"^$", catalog_views.index, name="home"),
    re_path(
        r"^catalog/",
        include(("librehatti.catalog.urls", "catalog"), namespace="catalog"),
    ),
    re_path(
        r"^useraccounts/",
        include(
            ("useraccounts.urls", "useraccounts"), namespace="useraccounts"
        ),
    ),
    re_path(
        r"^print/",
        include(("librehatti.prints.urls", "print"), namespace="print"),
    ),
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^search/", reports_views.search_form, name="search_form"),
    re_path(r"^search_result/", SearchResult.as_view(), name="search_result"),
    re_path(r"^save_fields", reports_views.save_fields, name="save_fields"),
    re_path(
        r"^list_saved_registers",
        reports_views.list_saved_registers,
        name="list_saved_registers",
    ),
    re_path(
        r"daily_result",
        register.daily_report_result,
        name="daily_report_result",
    ),
    re_path(
        r"consultancy_funds_report",
        register.consultancy_funds_report,
        name="consultancy_funds_report",
    ),
    re_path(
        r"tds_report", register.tds_report_result, name="tds_report_result"
    ),
    re_path(
        r"payment_report", register.payment_register, name="payment_register"
    ),
    re_path(
        r"suspense_clearance_register",
        register.suspense_clearance_register,
        name="suspense_clearance_register",
    ),
    re_path(
        r"servicetax", register.servicetax_register, name="servicetax_register"
    ),
    re_path(r"^main_register", register.main_register, name="main_register"),
    re_path(
        r"^proforma_register",
        register.proforma_register,
        name="proforma_register",
    ),
    re_path(
        r"^non_payment_register",
        register.non_payment_register,
        name="non_payment_register",
    ),
    re_path(
        r"^client_register", register.client_register, name="client_register"
    ),
    re_path(
        r"^material_report", register.material_report, name="material_report"
    ),
    re_path(r"^lab_report", register.lab_report, name="lab_report"),
    re_path(
        r"^suspense_register",
        register.suspense_register,
        name="suspense_register",
    ),
    re_path(
        r"^registered_users", register.registered_users, name="registered_users"
    ),
    re_path(
        r"^filter_sub_category/",
        reports_views.filter_sub_category,
        name="filter_sub_category",
    ),
    re_path(r"^bill/", prints_views.bill, name="bill"),
    re_path(
        r"^suspense_bill/", prints_views.suspense_bill, name="suspense_bill"
    ),
    re_path(r"^quoted_bill/", prints_views.quoted_bill, name="quoted_bill"),
    re_path(
        r"^bills/",
        include(("librehatti.bills.urls", "bills"), namespace="bills"),
    ),
    re_path(
        r"^suspense/",
        include(("librehatti.suspense.urls", "suspense"), namespace="suspense"),
    ),
    re_path(
        r"^generate_register/", GenerateRegister.as_view(), name="view_register"
    ),
    re_path(r"^history/", previous_history.history, name="history"),
    re_path(r"^details/", previous_history.details, name="details"),
    re_path(
        r"^proforma_details/",
        previous_history.proforma_details,
        name="proforma_details",
    ),
    re_path(r"^admin/doc/", include("django.contrib.admindocs.urls")),
    re_path(r"^admin/lookups/", include(ajax_select_urls)),
    re_path(
        r"^voucher/",
        include(("librehatti.voucher.urls", "voucher"), namespace="voucher"),
    ),
    re_path(
        r"^tinymce/", include(("tinymce.urls", "tinymce"), namespace="tinymce")
    ),
    re_path(
        r"^programmeletter/",
        programmeletter_views.programmeletter,
        name="programmeletter",
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/librehatti/suspense/models.py
# -*- coding: utf-8 -*-
import datetime

from django.db import models
from librehatti.catalog.models import Category, PurchaseOrder
from librehatti.voucher.models import FinancialSession


class SuspenseOrder(models.Model):
    """
    Stores order with over head costs.
    """

    voucher = models.IntegerField()
    purchase_order = models.ForeignKey(PurchaseOrder, on_delete=models.CASCADE)
    session_id = models.ForeignKey(FinancialSession, on_delete=models.CASCADE)
    distance_estimated = models.IntegerField(default=0)
    is_cleared = models.BooleanField(default=False)

    def __str__(self):
        return "%s" % (self.id)


class SuspenseClearance(models.Model):
    """
    Stores clearance of suspense orders.
    """

    session = models.ForeignKey(FinancialSession, on_delete=models.CASCADE)
    voucher_no = models.IntegerField()
    work_charge = models.IntegerField(blank=True, null=True)
    labour_charge = models.IntegerField(blank=True, null=True)
    car_taxi_charge = models.IntegerField(blank=True, null=True)
    boring_charge_external = models.IntegerField(blank=True, null=True)
    boring_charge_internal = models.IntegerField(blank=True, null=True)
    lab_testing_staff = models.CharField(max_length=200, blank=True, null=True)
    field_testing_staff = models.CharField(
        max_length=200, blank=True, null=True
    )
    test_date = models.CharField(max_length=600, blank=True, null=True)
    clear_date = models.DateField()


class Department(models.Model):
    """
    Stores department.
    """

    title = models.CharField(max_length=50)
    address = models.CharField(max_length=150)
    phone = models.CharField(max_length=20, blank=True)
    dean = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.title


class StaffPosition(models.Model):
    """
    Stores position of staff.
    """

    position = models.CharField(max_length=50)
    rank = models.IntegerField()

    def __str__(self):
        return self.position


class Staff(models.Model):
    """
    Stores staff and map it with position.
    """

    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    code = models.CharField(max_length=5)
    name = models.CharField(max_length=50)
    daily_ta_da = models.IntegerField(blank=True)
    position = models.ForeignKey(StaffPosition, on_delete=models.CASCADE)
    seniority_credits = models.IntegerField()
    always_included = models.BooleanField(default=True)
    lab = models.ForeignKey(Category, on_delete=models.CASCADE)
    email = models.EmailField(blank=True)

    class Meta:
        verbose_name_plural = "Staff"

    def __str__(self):
        return self.name


class TaDa(models.Model):
    """
    Model to store transport and daily allowances.
    """

    date_of_generation = models.DateField(default=datetime.date.today)
    voucher_no = models.IntegerField()
    session = models.IntegerField()
    departure_time_from_tcc = models.TimeField()
    arrival_time_at_site = models.TimeField()
    departure_time_from_site = models.TimeField()
    arrival_time_at_tcc = models.TimeField()
    tada_amount = models.IntegerField()
    tada_amount_without_tax = models.IntegerField()
    start_test_date = models.DateField()
    end_test_date = models.DateField()
    source_site = models.CharField(max_length=100, default="GNDEC, Ludhiana")
    testing_site = models.CharField(max_length=100)
    testing_staff = models.CharField(max_length=100)

    def __str__(self):
        return self.suspense


class TaDa_Tax_Detail(models.Model):
    tada = models.ForeignKey(TaDa, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    amount = models.IntegerField()


class QuotedSuspenseOrder(models.Model):
    """
    Stores Quoted suspense order.
    """

    quoted_order = models.ForeignKey(
        "bills.QuotedOrder", on_delete=models.CASCADE
    )
    distance_estimated = models.IntegerField(default=0)
    is_cleared = models.BooleanField(default=False)

    def __str__(self):
        return "%s" % (self.id)


class Vehicle(models.Model):
    """
    Stores vehicle details.
    """

    vehicle_id = models.CharField(max_length=20)
    vehicle_no = models.CharField(max_length=20)
    vehicle_name = models.CharField(max_length=20)

    def __str__(self):
        return "%s" % (self.vehicle_no)


class Transport(models.Model):
    """
    Stores Transportation details.
    """

    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    kilometer = models.CharField(max_length=500)
    rate = models.FloatField(default=10.0)
    date_of_generation = models.DateField()
    date = models.CharField(blank=True, max_length=600)
    total = models.IntegerField()
    voucher_no = models.IntegerField()
    session = models.ForeignKey(FinancialSession, on_delete=models.CASCADE)
    """def save(self, *args, **kwargs):

        # Now decode the kilometers
        jsonkilometer = simplejson.loads(self.kilometer)
        total_km = 0;

        # calculate the total kms
        for km in jsonkilometer:
            total_km += float(km)

        # Now calculate the total and save it in model
        self.total = total_km * self.rate
        super(Transport, self).save(*args, **kwargs)
    """

    class Meta:
        verbose_name_plural = "Transport"

    def __str__(self):
        return "%s" % (self.vehicle)


class TransportBillOfSession(models.Model):
    transport = models.ForeignKey(Transport, on_delete=models.CASCADE)
    transportbillofsession = models.IntegerField()
    session = models.ForeignKey(FinancialSession, on_delete=models.CASCADE)


class SuspenseClearedRegister(models.Model):
    suspenseclearednumber = models.IntegerField()
    voucher_no = models.IntegerField()
    session = models.ForeignKey(FinancialSession, on_delete=models.CASCADE)


class CarTaxiAdvance(models.Model):
    voucher_no = models.IntegerField()
    session = models.ForeignKey(FinancialSession, on_delete=models.CASCADE)
    spent = models.IntegerField()
    advance = models.IntegerField()
    balance = models.IntegerField()
    receipt_no = models.IntegerField()
    receipt_session = models.IntegerField()

src/templates/suspense/add_distance.html
{% extends 'base.html' %}
{% load i18n %} {% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
    <title>Add Distance</title>
    {% endblock %}
</head>
<body>
  {% block content %}
  <form method = 'POST' class="form-horizontal" action = ''>
      {% csrf_token %}
      <table class='add_distance'>
        <tr>
            <td style="display:none;">Order:<input type="text" name = "order" class = "order" size="7"
             id="order" value="{{purchase_order_id}}">
         </td>
     </tr>
     {% for value in voucher %}
     <tr>
        <td>Vocher:<input type="text" name = "voucher" class = "voucher form-control" size="7"
         id="voucher_{{value.voucher_no}}" value="{{value.voucher_no}}"></td>
         <td>Material:<input type="text" name = "material" class = "material form-control" size="35"
             id="material_{{value.voucher_no}}"
             value="{{value.purchased_item__item__category__name}}"></td>
             <td>Distance:<input type="text" name="distance" class = "distance form-control" size = "7"
                 id="distance_{{value.voucher_no}}" value="0"></td>
             </tr>
             {% endfor %}
         </table>
         <div id="add_distance_div">
         <input type='submit' class="btn btn-info btn-large adddistancesave" value = 'Next'>
        </div>
     </form>
     {% endblock %}
</body>

src/templates/suspense/car_taxi_advance_form.html
{% extends "base.html" %} {% load static %}

<html>
<head>
    {% block title %}
    <title>Form</title>
    {% endblock %}
</head>
<body>
    {% block content %}
    {% if car_taxi_advance %}
    <form method="POST" action={% url 'suspense:car_taxi_advance' %} >
        {% else %}
        <form method="POST" action=''>
            {% endif %}
            {% if messages %}
                <div class="alert alert-success">
                    {{ messages }}
                </div>
                {% endif %}
            {% csrf_token %}
            <table>
              {% if message %}
              <div class="alert alert-danger">
                  {{ message }}
              </div>
              {% endif %}
              {{form.as_table}}
          </table>
          <input type="submit" class="btn btn-info btn-large" value="Submit" id="button1">
      </form>
      {% endblock %}
  </body>
  </html>

src/templates/suspense/car_taxi_advance_success.html
{% extends 'base_register.html' %}
{% load i18n %} {% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
   {% block title %}
   <title>Order added</title>
   {% endblock %}
</head>
<body>
  {% block content %}
  <div class='order-success'>
   <p class='success-message'>Values saves <span class='green'>
      Successfully</span></p>
   </div>
   {% endblock %}
</body>
</html>

src/templates/suspense/clearance_options.html
{% extends 'base_register.html' %}
{% load i18n %} {% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
   {% block title %}
   <title>Clearance Options</title>
   {% endblock %}
</head>
<body>
  {% block content %}
  <div class='order-success'>
   <p class='success-message'>Clearance Options</p>
      <table>
      <tr>
          <th>Order No.</th>
          <td>{{order_id}}</td>
       </tr>
       <tr>
          <th>Voucher No.</th>
          <td>{{voucher_no}}</td>
       </tr>
       <tr>
          <th>Session:</th>
          <td>{{financialsession.session_start_date}} : {{financialsession.session_end_date}}</td>
       </tr>
       <tr>
          <th>Client:</th>
          <td>{{details.buyer__first_name}}&nbsp;{{details.buyer__last_name}}
           &nbsp;{{details.buyer__customer__title}}</td>
       </tr>
       <tr>
           <th>Address:</th>
           <td>{{details.buyer__customer__address__street_address}}&nbsp;
              {{details.buyer__customer__address__district}}</td>
          </tr>
          <tr>
           <th>Mode Of Payment:</th>
           <td>{{details.mode_of_payment__method}}</td>
       </tr>
   </table>
   <div class='order-success-options'>
    <table>
        <tr>
           <th colspan='3'><h3>Options</h3></th>
       </tr>
       <tr>
         {% if with_transport == 0 %}
           <td><a target="_blank" href = '{% url 'suspense:with_transport' %}?voucher_no={{voucher_no}}&session={{session_id}}'><input type="button" class="btn btn-info btn-large" name="" value="with transport"></a></td>

           <form id="myForm" action="{% url 'suspense:transport_bill' %}" method="post">
           {% csrf_token %}
           <td><input type="submit" class="btn btn-info btn-large" value="Transport Bill"/></td>
             <input type="hidden" value="{{ session_id }}" name="session" />
             <input type="hidden" value="{{ voucher_no }}" name="voucher" />
           </td>
           </form>
          {% else %}
          <td><a  target="_blank" href = '{% url 'suspense:with_transport' %}?voucher_no={{voucher_no}}&session={{session_id}}'><input type="button" class="btn btn-info btn-large" name="" value="without transport"></a></td>
          {% endif %}
           <td><a target="_blank" href = '{% url 'suspense:other_charges' %}?voucher_no={{voucher_no}}&session={{session_id}}'><input type="button" class="btn btn-info btn-large" name="" value="Other Charges"></a></td>

         <form id="myForm" action="{% url 'suspense:tada_bill_list' %}" method="post">
           {% csrf_token %}
           <td><input type="submit" class="btn btn-info btn-large" value="TA/DA Bill" name='button1' id='button1' /></td>
             <input type="hidden" value="{{ session_id }}" name="session" />
             <input type="hidden" value="{{ voucher_no }}" name="voucher" />
           </form>

       </tr>
    </table>
       </div>
   </div>
   {% endblock %}
</body>
</html>

src/templates/suspense/clearance_result.html
{% extends "base.html" %}
<html>
<head>
    {% block title %}
    <title>
        Suspense Job
    </title>
    <style type="text/css">
    .clearance_table{
        width: 200% !important;
        margin-top: 50px;
    }
    </style>
    {% endblock %}
</head>
<body>
    {% block content %}
    <div class='clearance-success'>
        <p class='success-message'>Clearance <span class='green'>
            Successful</span></p></div>
            <div class="clearance_table">
            <table>
                <tr>
                    <th>Session:</th>
                    <td>{{session}}</td>
                </tr>
                <tr>
                    <th>Voucher No.</th>
                    <td>{{voucher_no}}</td>
                </tr>
                <tr>
                    <th>Labour Charge:</th>
                    <td>{{labour_charge}}</td>
                </tr>
                <tr>
                    <th>Car Taxi Charge:</th>
                    <td>{{car_taxi_charge}}</td>
                </tr>
                <tr>
                    <th>Boring Charge External:</th>
                    <td>{{boring_charge_external}}</td>
                </tr>
                <tr>
                    <th>Boring Charge Internal:</th>
                    <td>{{boring_charge_internal}}</td>
                </tr>
                <tr>
                    <th>Lab Testing Staff:</th>
                    <td>{{lab_testing_staff}}</td>
                </tr>
                <tr>
                    <th>field Testing Staff:</th>
                    <td>{{field_testing_staff}}</td>
                </tr>
                <tr>
                    <th>Test Date:</th>
                    <td>{{test_date}}</td>
                </tr>
                <tr>
                    <th>Clear Date:</th>
                    <td>{{clear_date}}</td>
                </tr>
            </table>
            </div>
    {% endblock %}
</body>
</html>

src/templates/suspense/form.html
{% extends "base.html" %}

<html>
{% block title %}
<title>Form</title>
{% endblock %}
<body>
  {% block content %}
  {% if errors %}
  <div class="alert alert-danger">
    {{ errors }}
  </div>
  {% endif %}
  {% if tada %}
  <form method="POST" action={% url 'suspense:tada_result' %} >
    {% else %}
    <form method="POST" action=''>
      {% endif %}
      {% csrf_token %}
      <table>
       {% if message %}
       <div class="alert alert-danger">
         {{ message }}
       </div>
       {% endif %}
       {% if messages %}
       <div class="alert alert-success">
        {{ messages }}
      </div>
      {% endif %}
       {{form.as_table}}
     </table>
     <input type="submit" class="btn btn-info btn-large" value="Submit" id="button1">
   </form>
   {% endblock %}
 </body>
 </html>

src/templates/suspense/othercharge.html
{% extends 'bill_base.html' %}
<html>
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/voucher.css' %}">

    {% block title %}
    <title>Other Charges</title>
    {% endblock %}
</head>

<body>
    {% block content %}
    <div class="othertable">
      <table>
        <tr>
          <td>OT Vr. No.</td>
          <td>{{ voucher_no }}</td>
        </tr>
        <tr>
          <td>Date:</td>
          <td>_________</td>
        </tr>
      </table>
    </div>
    <div style="clear:both;">
        </div>
    <div>A sum of &#8377; {{complete_total}}/- (TA/DA staff &#8377; {{ta_da}}, Other charges &#8377; {{transplusother}}/- has been deposited by:-
    </div>
    <div>
    {% if address.purchase_order__buyer__first_name %}
    {{address.purchase_order__buyer__first_name}} {{address.purchase_order__buyer__last_name}}
    {% else %}
    {{address.purchase_order__buyer__customer__title}}
    {% endif %}
    , {{address.purchase_order__buyer__customer__address__street_address}}, {{address.purchase_order__buyer__customer__address__district}}
    {% if address.purchase_order__buyer__customer__address__pin != 'None' and address.purchase_order__buyer__customer__address__pin != '' %}
    , {{address.purchase_order__buyer__customer__address__pin}}
    {% endif %}
       , {{address.purchase_order__buyer__customer__address__province}}</div>
        <div>Vide receipt no. {{purchase_order}} dated {{order_date}} and was transferred vide S.C. no.________dated________</div>
        <div>A sum of &#8377; {{total}}/- was spent for testing on {{test_date}} as detailed below.</div>
        <br>
        <div id = "othercharges">
            <table border='1px'>
                <tr>
                    <td>T.A/D.A Staff </td>
                    <td  id = "pos-right">{{ ta_da }}</td>
                </tr>
                <tr>
                    <td>Boring Charges </td>
                    <td  id = "pos-right">{{boring_charges}}</td>
                </tr>
                <tr>
                    <td>Labour Charges </td>
                    <td  id = "pos-right">{{ suspense_clearance.labour_charge }}</td>
                </tr>
                <tr>
                    <td>Car/Taxi Charges </td>
                    <td  id = "pos-right">{{ suspense_clearance.car_taxi_charge }}</td>
                </tr>
                <tr>
                    <td><b>TOTAL</b></td>
                    <td  id = "pos-right"><b>{{total}}</b></td>
                </tr>
            </table>
        </div>
        <div class="position">
        {% if car_taxi_advance %}
        &#8377; {{car_taxi_advance.spent}}/- spent against advance &#8377; {{car_taxi_advance.advance}}/- the balance amount &#8377; {{car_taxi_advance.balance}}/- deposit within cashier vide receipt No. {{car_taxi_advance.receipt_no}} dated {{receipt_dated.purchase_order__date_time}}.
        {% endif %}
        {% if transport != 0 %}
        The Transport Bill No. {{transportbillno.transportbillofsession}} dated {{transport.date_of_generation}} for &#8377; {{transport.total}}/- is attached. The sum of &#8377; {{transport.total}}/- may be transferred from other charges to Consultancy Transport Fund.
        {% endif %}
        {% if car_taxi_advance %}
        {% else %}
        The sum of &#8377; {{total}}/- spent  by Dean Testing & Consultancy may Please be paid to him.
            {% endif %}
        </div>
        <div class = "footer1">DEAN Testing and Consultancy
        </div>
        {% endblock %}
</body>
</html>

src/templates/suspense/quoted_add_distance.html
{% extends 'base.html' %}
{% load i18n %} {% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
    <title>Add Distance</title>
    {% endblock %}
</head>
<body>
  {% block content %}

  <form method = 'POST' class="form-horizontal" action = ''>
      {% csrf_token %}
      <table>
        <tr>
            <td>Order:<input type="text" name = "order" readonly="readonly" class = "quoteorder form-control" size="7"
               id="quoteorder" value="{{quoted_order_id}}"></td>
            <td>Distance:<input type="text" name="distance" class = "quotedistance form-control" size = "7"
               id="quotedistance" value="0"></td>
        </tr>
       </table>
       <input type='submit' class="btn btn-info btn-large quotedadddistancesave" value = 'Next'>
   </form>
   {% endblock %}
</body>

src/templates/suspense/suspense_first.html
{% extends "base.html" %} {% load static %}

<html>
<head>
    {% block title %}
    <title>Form</title>
    {% endblock %}
</head>
<body>
    {% block content %}
    {% if clearance %}
    <form method="POST" action={% url 'suspense:clearance_result' %} >
        {% else %}
        <form method="POST" action=''>
            {% endif %}
            {% if messages %}
                <div class="alert alert-success">
                    {{ messages }}
                </div>
                {% endif %}
            {% csrf_token %}
            <table>
              {% if message %}
              <div class="alert alert-danger">
                  {{ message }}
              </div>
              {% endif %}
              {{form.as_table}}
          </table>
          <input type="submit" class="btn btn-info btn-large" value="Submit" id="button1">
      </form>
      {% endblock %}
  </body>
  </html>

src/templates/suspense/transport_summary.html
{% extends 'base_register.html' %}
{% load i18n %} {% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
   {% block title %}
   <title>Order added</title>
   {% endblock %}
</head>
<body>
  {% block content %}
  <div class='order-success'>
   <p class='success-message'>Charges added <span class='green'>
      Successfully</span></p>
    <div id = "transport_content">

        <table border="1" align="center">
            <tr>
                <th>Date of Use</th>
                <th>Distance(in Kms)</th>
                <th>Rate</th>
                <th>Amount</th>
            </tr>
            {% for date,km,amount in zip_data %}
            <tr>
                <td>
                    {{ date }}
                </td>
                <td>
                    {{ km }}
                </td>
                <td>
                    {{ rate }}
                </td>
                <td>
                    {{ amount }}
                </td>
            </tr>
            {% endfor %}
            <tr>
                <td colspan = "3"><center><b>Total</b></center></td>
                <td> {{ total_amount }}</td>
            </tr>
        </table>
         <div class='order-success-options'>
    <table>
       <tr>
           <td></td>
           <form id="myForm" action="{% url 'suspense:transport_bill' %}" method="post">
           {% csrf_token %}
           <td><input type="submit" class="btn btn-info btn-large" value="Generate Bill" name='button1' id='button1' /></td>
             <input type="hidden" value="{{ session }}" name="session" />
             <input type="hidden" value="{{ voucherid }}" name="voucher" />


           </form>
           <td></td>
       </tr>
           </table>
       </div>
    </div>
   </div>
   {% endblock %}
</body>
</html>

src/templates/suspense/transportform.html
{% extends "base.html" %}

{% block extrastyle %}
{% endblock %}

{% block extrajs %}
<script type="text/javascript">
    $(document).ready(function() {
        $("[name='date']").datepicker({
            changeMonth: true,
            changeYear: true,dateFormat:"yy-mm-dd"
        });
        $("#button2").click(function() {

        //Insert just after the kilo input in p element
        $("#id_kilometer").parent("p").clone().insertAfter($("#id_date").parent("p"));
        var dateelement = $("#id_date").parent("p").clone();
        var newdateelement = $("<input class='form-control' type='text' name='date' />");

        //We have to replace the date field with new one everytime as browser
        //will confuse it with the cloned element and events will not work
        dateelement.children("input[name='date']").replaceWith(newdateelement);
        dateelement.insertAfter($("#id_date").parent("p"));
        $("[name='date']").datepicker({
            changeMonth: true,
            changeYear: true,dateFormat:"yy-mm-dd"
        });
    });
    });
</script>
{% endblock %}
{% block content %}
<table>
    <tr>
        <td>
            <form action='{% url 'suspense:transportbill' %}' method='POST'>
                {% if messages %}
                <div class="alert alert-success">
                    {{ messages }}
                </div>
                {% endif %}
                {% if message %}
                <div class="alert alert-danger">
                    {{ message }}
                </div>
                {% endif %}
                {% csrf_token %}
                {{TransportForm.as_p}}
                <input type="hidden" value="{{ session }}" name="session" />
                <input type="hidden" value="{{ voucher }}" name="voucher" />

                <input type="submit" class="btn btn-info btn-large" value="Generate Bill" name='button1' id='button1' />
                <input type="button" class="btn btn-info btn-large" value="Add Another" name='button2' id='button2' />
            </form>
        </td>
    </tr>
</table>
{% endblock %}