src/librehatti/suspense/urls.py
# -*- coding: utf-8 -*-
from django.urls import re_path

from . import views


urlpatterns = [
    re_path(r"^add_distance", views.add_distance, name="add_distance"),
    re_path(r"^clresult/", views.clearance_result, name="clearance_result"),
    re_path(r"^clsearch/", views.clearance_search, name="clearance_search"),
    re_path(r"^othercharges/", views.other_charges, name="other_charges"),
    re_path(r"^tada_result/", views.tada_result, name="tada_result"),
    re_path(
        r"^tada_order_session/",
        views.tada_order_session,
        name="tada_order_session",
    ),
    re_path(r"^with_transport/", views.with_transport, name="with_transport"),
    re_path(r"^transport/", views.transport, name="transport"),
    re_path(r"^transportbill/", views.transportbill, name="transportbill"),
    re_path(
        r"^quoted_add_distance",
        views.quoted_add_distance,
        name="quoted_add_distance",
    ),
    re_path(
        r"^quoted_save_distance",
        views.quoted_save_distance,
        name="quoted_save_distance",
    ),
    re_path(r"^save_distance", views.save_distance, name="save_distance"),
    re_path(r"^sessionselect/", views.sessionselect, name="sessionselect"),
    re_path(r"^mark_clear/", views.mark_clear, name="mark_clear"),
    re_path(r"^mark_status/", views.mark_status, name="mark_status"),
    re_path(
        r"^clearance_options/",
        views.clearance_options,
        name="clearance_options",
    ),
    re_path(r"^summary_page/", views.summary_page, name="summary_page"),
    re_path(r"^transport_bill/", views.transport_bill, name="transport_bill"),
    re_path(r"^tada_bill/", views.tada_bill, name="tada_bill"),
    re_path(r"^tada_bill_list/", views.tada_bill_list, name="tada_bill_list"),
    re_path(
        r"^car_taxi_advance_form/",
        views.car_taxi_advance_form,
        name="car_taxi_advance_form",
    ),
    re_path(
        r"^car_taxi_advance/", views.car_taxi_advance, name="car_taxi_advance"
    ),
]

src/librehatti/urls.py
# -*- coding: utf-8 -*-
# from django.urls import patterns, include, url
from ajax_select import urls as ajax_select_urls
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path

from .catalog import views as catalog_views
from .prints import views as prints_views
from .programmeletter import views as programmeletter_views
from .reports import previous_history, register, views as reports_views
from .reports.register_generator import GenerateRegister
from .reports.search import SearchResult


admin.autodiscover()
urlpatterns = [
    path("api/auth/", include("djoser.urls.authtoken")),
    re_path(r"^$", catalog_views.index, name="home"),
    re_path(
        r"^catalog/",
        include(("librehatti.catalog.urls", "catalog"), namespace="catalog"),
    ),
    re_path(
        r"^useraccounts/",
        include(
            ("useraccounts.urls", "useraccounts"), namespace="useraccounts"
        ),
    ),
    re_path(
        r"^print/",
        include(("librehatti.prints.urls", "print"), namespace="print"),
    ),
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^search/", reports_views.search_form, name="search_form"),
    re_path(r"^search_result/", SearchResult.as_view(), name="search_result"),
    re_path(r"^save_fields", reports_views.save_fields, name="save_fields"),
    re_path(
        r"^list_saved_registers",
        reports_views.list_saved_registers,
        name="list_saved_registers",
    ),
    re_path(
        r"daily_result",
        register.daily_report_result,
        name="daily_report_result",
    ),
    re_path(
        r"consultancy_funds_report",
        register.consultancy_funds_report,
        name="consultancy_funds_report",
    ),
    re_path(
        r"tds_report", register.tds_report_result, name="tds_report_result"
    ),
    re_path(
        r"payment_report", register.payment_register, name="payment_register"
    ),
    re_path(
        r"suspense_clearance_register",
        register.suspense_clearance_register,
        name="suspense_clearance_register",
    ),
    re_path(
        r"servicetax", register.servicetax_register, name="servicetax_register"
    ),
    re_path(r"^main_register", register.main_register, name="main_register"),
    re_path(
        r"^proforma_register",
        register.proforma_register,
        name="proforma_register",
    ),
    re_path(
        r"^non_payment_register",
        register.non_payment_register,
        name="non_payment_register",
    ),
    re_path(
        r"^client_register", register.client_register, name="client_register"
    ),
    re_path(
        r"^material_report", register.material_report, name="material_report"
    ),
    re_path(r"^lab_report", register.lab_report, name="lab_report"),
    re_path(
        r"^suspense_register",
        register.suspense_register,
        name="suspense_register",
    ),
    re_path(
        r"^registered_users", register.registered_users, name="registered_users"
    ),
    re_path(
        r"^filter_sub_category/",
        reports_views.filter_sub_category,
        name="filter_sub_category",
    ),
    re_path(r"^bill/", prints_views.bill, name="bill"),
    re_path(
        r"^suspense_bill/", prints_views.suspense_bill, name="suspense_bill"
    ),
    re_path(r"^quoted_bill/", prints_views.quoted_bill, name="quoted_bill"),
    re_path(
        r"^bills/",
        include(("librehatti.bills.urls", "bills"), namespace="bills"),
    ),
    re_path(
        r"^suspense/",
        include(("librehatti.suspense.urls", "suspense"), namespace="suspense"),
    ),
    re_path(
        r"^generate_register/", GenerateRegister.as_view(), name="view_register"
    ),
    re_path(r"^history/", previous_history.history, name="history"),
    re_path(r"^details/", previous_history.details, name="details"),
    re_path(
        r"^proforma_details/",
        previous_history.proforma_details,
        name="proforma_details",
    ),
    re_path(r"^admin/doc/", include("django.contrib.admindocs.urls")),
    re_path(r"^admin/lookups/", include(ajax_select_urls)),
    re_path(
        r"^voucher/",
        include(("librehatti.voucher.urls", "voucher"), namespace="voucher"),
    ),
    re_path(
        r"^tinymce/", include(("tinymce.urls", "tinymce"), namespace="tinymce")
    ),
    re_path(
        r"^programmeletter/",
        programmeletter_views.programmeletter,
        name="programmeletter",
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/librehatti/voucher/urls.py
# -*- coding: utf-8 -*-
from django.urls import re_path

from . import views


urlpatterns = [
    re_path(
        r"^voucher_generate/", views.voucher_generate, name="voucher_generate"
    ),
    re_path(r"^voucher_show/", views.voucher_show, name="voucher_show"),
    re_path(r"^voucher_print/", views.voucher_print, name="voucher_print"),
]

src/librehatti/voucher/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.db.models import Max
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from librehatti.catalog.models import (
    Bill,
    FinancialSession,
    HeaderFooter,
    PurchaseOrder,
    PurchasedItem,
    SpecialCategories,
    TaxesApplied,
)
from librehatti.catalog.request_change import request_notify
from librehatti.prints.helper import num2eng
from librehatti.suspense.models import Staff, SuspenseOrder
from librehatti.voucher.models import (
    CalculateDistribution,
    CategoryDistributionType,
    Distribution,
    VoucherId,
    VoucherTotal,
)
from useraccounts.models import Customer


@login_required
def voucher_generate(request):
    """
    This function calculates the session id and then initialise or increment
    voucher number according to the previous purchase order's session id
    Argument:Http Request
    Return:Response Redirect to add distance function
    """
    old_post = request.session.get("old_post")
    purchase_order_id = request.session.get("purchase_order_id")
    generate_voucher = 1
    first_item = PurchasedItem.objects.values("item__category__id").filter(
        purchase_order=purchase_order_id
    )[0]
    category_check = SpecialCategories.objects.filter(
        category=first_item["item__category__id"]
    )
    if category_check:
        specialcategories = SpecialCategories.objects.values("voucher").filter(
            category=first_item["item__category__id"]
        )[0]
        if not specialcategories["voucher"]:
            generate_voucher = 0
    purchase_order = PurchaseOrder.objects.values("id", "date_time").get(
        id=purchase_order_id
    )
    purchase_order_id = purchase_order["id"]
    purchase_order_date = purchase_order["date_time"]
    financialsession = FinancialSession.objects.values(
        "id", "session_start_date", "session_end_date"
    )
    for value in financialsession:
        start_date = value["session_start_date"]
        end_date = value["session_end_date"]
        if start_date <= purchase_order_date <= end_date:
            session_id = value["id"]
    purchased_item = (
        PurchasedItem.objects.values_list("item__category", flat=True)
        .filter(purchase_order=purchase_order_id)
        .order_by("item__category")
    )
    purchased_item_id = (
        PurchasedItem.objects.values_list("id", flat=True)
        .filter(purchase_order=purchase_order_id)
        .order_by("item__category")
    )
    voucherno = 0
    purchaseditemofsession = 0
    item = 0
    session = FinancialSession.objects.get(id=session_id)
    poi = PurchaseOrder.objects.get(id=purchase_order_id)
    max_id = VoucherId.objects.all().aggregate(Max("id"))
    if max_id["id__max"] is None:
        voucherno = 1
        is_special_var = 0
        purchaseditemofsession = 1
        for value in purchased_item:
            if generate_voucher == 0:
                voucherno = 0
                is_special_var = 1
            distribution_type = CategoryDistributionType.objects.values(
                "distribution"
            ).get(category=purchased_item[item])
            distribution = Distribution.objects.values(
                "id", "ratio", "college_income", "admin_charges"
            ).get(id=distribution_type["distribution"])
            distribution_id = Distribution.objects.get(
                id=distribution_type["distribution"]
            )
            voucherid = VoucherId(
                purchase_order=poi,
                purchased_item=PurchasedItem.objects.get(
                    pk=purchased_item_id[item]
                ),
                voucher_no=voucherno,
                purchase_order_of_session=1,
                purchased_item_of_session=purchaseditemofsession,
                session=session,
                distribution=distribution_id,
                ratio=distribution["ratio"],
                college_income=distribution["college_income"],
                admin_charges=distribution["admin_charges"],
                is_special=is_special_var,
            )
            voucherid.save()
            try:
                if purchased_item[item] == purchased_item[item + 1]:
                    purchaseditemofsession = purchaseditemofsession + 1
                    item = item + 1
                else:
                    voucherno = voucherno + 1
                    purchaseditemofsession = purchaseditemofsession + 1
                    item = item + 1
            except BaseException:
                continue
    else:
        voucherid = VoucherId.objects.values(
            "voucher_no",
            "purchase_order_of_session",
            "purchased_item_of_session",
            "session",
        ).get(id=max_id["id__max"])
        if voucherid["voucher_no"] == 0:
            temp_obj = VoucherId.objects.values("id").filter(
                is_special=0, session=session
            )
            if temp_obj:
                for temp_val in temp_obj:
                    maxid = temp_val["id"]
                voucherid_temp = VoucherId.objects.values("voucher_no").get(
                    id=maxid
                )
                voucherid["voucher_no"] = voucherid_temp["voucher_no"]
            else:
                voucherid["voucher_no"] = 0
        pre_purchase_order_session = voucherid["session"]
        voucher_no = voucherid["voucher_no"]
        purchase_order_of_session = voucherid["purchase_order_of_session"] + 1
        purchased_item_of_session = voucherid["purchased_item_of_session"]
        if session_id == pre_purchase_order_session:
            voucherno = voucher_no + 1
            is_special_var = 0
            purchaseditemofsession = purchased_item_of_session + 1
            for value in purchased_item:
                if generate_voucher == 0:
                    voucherno = 0
                    is_special_var = 1
                distribution_type = CategoryDistributionType.objects.values(
                    "distribution"
                ).get(category=purchased_item[item])
                distribution = Distribution.objects.values(
                    "id", "ratio", "college_income", "admin_charges"
                ).get(id=distribution_type["distribution"])
                distribution_id = Distribution.objects.get(
                    id=distribution_type["distribution"]
                )
                voucherid = VoucherId(
                    purchase_order=poi,
                    purchased_item=PurchasedItem.objects.get(
                        pk=purchased_item_id[item]
                    ),
                    voucher_no=voucherno,
                    purchase_order_of_session=purchase_order_of_session,
                    purchased_item_of_session=purchaseditemofsession,
                    session=session,
                    distribution=distribution_id,
                    ratio=distribution["ratio"],
                    college_income=distribution["college_income"],
                    admin_charges=distribution["admin_charges"],
                    is_special=is_special_var,
                )
                voucherid.save()
                try:
                    if purchased_item[item] == purchased_item[item + 1]:
                        purchaseditemofsession = purchaseditemofsession + 1
                        item = item + 1
                    else:
                        voucherno = voucherno + 1
                        purchaseditemofsession = purchaseditemofsession + 1
                        item = item + 1
                except BaseException:
                    continue
        else:
            voucherno = 1
            is_special_var = 0
            purchaseditemofsession = 1
            purchase_order_of_session = 1
            for value in purchased_item:
                if generate_voucher == 0:
                    voucherno = 0
                    is_special_var = 1
                distribution_type = CategoryDistributionType.objects.values(
                    "distribution"
                ).get(category=purchased_item[item])
                distribution = Distribution.objects.values(
                    "id", "ratio", "college_income", "admin_charges"
                ).get(id=distribution_type["distribution"])
                distribution_id = Distribution.objects.get(
                    id=distribution_type["distribution"]
                )
                voucherid = VoucherId(
                    purchase_order=poi,
                    purchased_item=PurchasedItem.objects.get(
                        pk=purchased_item_id[item]
                    ),
                    voucher_no=voucherno,
                    purchase_order_of_session=purchase_order_of_session,
                    purchased_item_of_session=purchaseditemofsession,
                    session=session,
                    distribution=distribution_id,
                    ratio=distribution["ratio"],
                    college_income=distribution["college_income"],
                    admin_charges=distribution["admin_charges"],
                    is_special=is_special_var,
                )
                voucherid.save()
                try:
                    if purchased_item[item] == purchased_item[item + 1]:
                        purchaseditemofsession = purchaseditemofsession + 1
                        item = item + 1
                    else:
                        voucherno = voucherno + 1
                        purchaseditemofsession = purchaseditemofsession + 1
                        item = item + 1
                except BaseException:
                    continue
    voucher_obj = (
        VoucherId.objects.values_list("id", flat=True)
        .filter(purchase_order=purchase_order_id)
        .order_by("id")
    )
    voucher_obj1 = (
        VoucherId.objects.values_list("purchased_item", flat=True)

src/templates/voucher/sessionselect.html
{% extends "base.html" %}
{% block content %}

<!--
modified  url 'suspense:sessionselect' to make compatible with django2.0
File LibreHatti/src/librehatti/suspense/urls.py uses namespace for sessionselect
-->

<form action='{% url 'suspense:sessionselect' %}' method='POST'>
                {% if errors %}
                <div class="alert alert-danger">
                    {{ errors }}
                </div>
                {% endif %}
                {% csrf_token %}
                <table>
                {{SelectForm.as_table}}
                </table>
        <input type="submit" class="btn btn-info btn-large" value="Submit" name='button1' id='button1' />
    </form>
{% endblock %}

src/templates/voucher/voucher_report.html
{% extends 'bill_base.html' %}
<html>
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/voucher.css' %}">
    {% block title %}
    <title>Voucher</title>
    {% endblock %}
</head>
<body>
	{% block content %}
    <br>
<div class='bill-left'>
	<span id='highlight'>
		Receipt No./Main Voucher:</span>
		{{ purchase_order }}/{{voucher}}
	<span id='dated'>
		<span id='highlight'>
			Dated:</span>
		{{date |date:"d M, Y"}}
	</span>
</div>
<br>
<div style="clear:both;">
        </div>
    <div class="designation">Principal,</div>
    <br>
    Received a sum of &#8377; {{calculate_distribution.total }}/- ( Rupees {{total_in_words}} only )
    Vide Cash from
    {% if buyer.buyer__first_name %}
    {{ buyer.buyer__first_name}} {{ buyer.buyer__last_name }}
    {% else %}
    {{buyer.buyer__customer__title}}
    {% endif %}
    , {{address.address__street_address}}, {{address.address__district}},
    {% if address.address__pin != 'None' and address.address__pin != '' %}
     {{address.address__pin}},
     {% endif %}
     {{address.address__province}}
     {% if buyer_name.company %}
      Agency: {{buyer.buyer__customer__company}}
        {% endif %} on account of {{material}}.
    <br/><br/>
    <div >Vide Receipt No. {{purchase_order }}  Dated: {{date}} </div>
    <div >Nature of Consultancy : {{ d_name }},  Ratio {{ ratio }} </div>
    <div id = "pos-left">
        <br/>
        <table border='1px'>
            <tr>
               <th colspan="3">The Distribution May Be Made As</th>
           </tr>
           <tr>
               <th rowspan="5">Credits</th>
               <td>College Income @ {{ college_income }}% </td>
               <td  id = "pos-right">{{ calculate_distribution.college_income_calculated }}</td>
           </tr>
           <tr>
               <td>Admin Charges @ {{ admin_charges }}% </td>
               <td  id = "pos-right">{{ calculate_distribution.admin_charges_calculated}}</td>
           </tr>
           <tr>
               <td>Consultant/Asstt. Share </td>
               <td  id = "pos-right">{{ calculate_distribution.consultancy_asset }}</td>
           </tr>
           <tr>
               <td>Development Funds (Consultancy) </td>
               <td  id = "pos-right">{{ calculate_distribution.development_fund }}</td>
           </tr>
           <tr>
               <td>Total (&#8377;) </td>
               <td  id = "pos-right">{{ calculate_distribution.total }}</td>
           </tr>
       </table>
   </div>
   <br>
   <br>
   <div>
    <table border='1px'>
        <tr>
           <th>Name Of Employees</th>
           <th>Designation</th>
       </tr>
       {% for emp in employee %}
       <tr>
           <td>{{emp.name}}</td>
           <td>{{emp.position__position}}</TD>
           </tr>
           {% endfor %}
       </table>
   </div>
   <div id = "pos-left">The Work Has Been Executed By The Persons Mentioned Above. </div>
   <br><br>
   <div id="voucher-no"><b>Accounts Clerk (Consultancy)</b>
    <div style = "text-align:right; float:right">
        <b>Dean Testing & Consultancy</b>
    </div>
</div>
{% endblock %}
</body>
</html>

src/templates/voucher/voucher_report_suspence.html
{% extends 'bill_base.html' %}
<html>
<head>
	{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/voucher.css' %}">
    {% block title %}
    <title>Voucher</title>
    {% endblock %}
</head>
<body>
	{% block content %}
    <br>
<div class='bill-left'>
	<span id='highlight'>
		Receipt No./Suspence Voucher:</span>
			{{ job }}/{{suspense_voucher}}
	<span id='dated'>
		<span id='highlight'>Dated:</span>
		{{date |date:"d M, Y"}}
	</span>
</div>
<br>
    <div style="clear:both;">
        </div>
    <div class="designation">Principal,</div>
    <br>
    A sum of &#8377; {{cost.amount_received}}/- ( Rupees {{ inwords }} only ) has been deposited by
    {% if buyer.buyer__first_name %}
    {{ buyer.buyer__first_name}} {{ buyer.buyer__last_name }}
    {% else %}
    {{buyer.buyer__customer__title}}
    {% endif %}
    , {{address.address__street_address}}, {{address.address__district}},
    {% if address.address__pin != 'None' and address.address__pin != '' %}
     {{address.address__pin}},
     {% endif %}
     {{address.address__province}} {% if buyer_name.company %}
      Agency: {{buyer.buyer__customer__company}}
        {% endif %} by {{method}}
      {% if method_id != 1 and method_id != 4 %}
      No. {{method_number}} dated {{method_date}}
      {% endif %}
      , on account of {{material}}.

    This amount is kept in suspence till clearance. <br/><br/>
    <div class="receipt-detail">Receipt No. {{job}}   </div>
    <div class="receipt-detail">Dated: {{date}}</div>
    <div id = "pos-left">
        <br>
        <table  border = "1px">
            <tr>
               <td>Bill Amount</td>
               <td id = "pos-right">{{cost.totalplusdelivery}}.00</td>
           </tr>
           {% for value in tax %}
           <tr>
               <td>{{ value.surcharge__tax_name }}  @ {{ value.surcharge__value }}% </td>
               <td  id = "pos-right">{{ value.tax }}.00</td>
           </tr>
           {% endfor %}
        <tr>
            <td>Total Amount </td>
            <td  id = "pos-right"> {{ cost.grand_total}}.00</td>
        </tr>
        <tr>
           <td>TDS</td>
           <td id = "pos-right">{{tds.tds}}.00</td>
       </tr>
       <tr>
           <td>Balance</td>
           <td id = "pos-right">{{cost.amount_received}}.00</td>
       </tr>
   </table>
</div>
<br><br>
<div id="voucher-no"><b>Accounts Clerk (Consultancy)</b>
    <div style = "text-align:right; float:right">
        <b>Dean Testing & Consultancy</b>
    </div>
</div>
{% endblock %}
</body>
</html>

src/templates/voucher/voucher_show.html
{% extends 'base_register.html' %}
<html>
<head>
    {% block title %}
    <title>
        Your Vouchers
    </title>
    {% endblock %}
    <style>
        .else { color : red ; }
        h1{text-align: center;}
        h2, .else { text-align :center; margin-top:5%; }
        table{display: inline-block;text-align: center;}
        table,th,td{border: 1px solid black; border-collapse: collapse;}
    </style>
</head>
<body>
    {% block content %}
    <div class="list-results">
        <h2>Voucher</h2>
        <div class="shrinked-table">
        {% if message != 'Voucher' %}
        <div class="alert alert-danger">
            <center>{{ message }}</center>
        </div>
        {% else %}
         <table border="1px">
            <tr>
                <th>Purchase Order</th>
                <th>Voucher No</th>
                <th>Options</th>
            </tr>
            <tr>
                {% if voucherid %}
                {% for value in voucherid %}
                <td>{{ value.purchase_order_of_session }}</td>
                <td>{{ value.voucher_no }}</td>
                <td><a target="_blank" href = '{% url 'voucher:voucher_print'%}?purchase_order={{value.purchase_order}}&voucher_no={{value.voucher_no}}&session={{value.session}}'>Generate Voucher</a>
                {% for suspense_voucher in suspense_order %}
                {% if suspense_voucher.voucher == value.voucher_no %}
                |
                <a href = '{% url 'suspense:clearance_options'%}?voucher_no={{value.voucher_no}}&session={{value.session}}'>Clearance Options</a>
                {% endif %}
                {% endfor %}
                </td>
            </tr>
            {% endfor %}
            {% endif %}
        </table>
    {% endif %}
    </div>
</div>
{% endblock %}
</body>
</html>