src/librehatti/catalog/urls.py
# -*- coding: utf-8 -*-
"""
urls of catalog are..
"""
# from django.urls import url, patterns
from django.urls import re_path

from . import request_change, views as catalog_views


app_name = "catalog"


urlpatterns = [
    re_path(r"^$", catalog_views.index, name="index"),
    re_path(
        r"^select_sub_category/",
        catalog_views.select_sub_category,
        name="select_sub_category",
    ),
    re_path(r"^jsreverse/", catalog_views.jsreverse, name="jsreverse"),
    re_path(r"^select_item/", catalog_views.select_item, name="select_item"),
    re_path(r"^bill_cal/", catalog_views.bill_cal, name="bill_cal"),
    re_path(
        r"^list_products/", catalog_views.list_products, name="list_products"
    ),
    re_path(
        r"^previous_value/", catalog_views.previous_value, name="previous_value"
    ),
    re_path(
        r"^order_added_success/",
        catalog_views.order_added_success,
        name="order_added_success",
    ),
    re_path(
        r"^change_request/", catalog_views.change_request, name="change_request"
    ),
    re_path(
        r"^price_per_unit/", catalog_views.price_per_unit, name="price_per_unit"
    ),
    re_path(r"^select_type/", catalog_views.select_type, name="select_type"),
    re_path(
        r"^nonpaymentorderofsession/",
        catalog_views.nonpaymentorderofsession,
        name="nonpaymentorderofsession",
    ),
    re_path(
        r"^nonpaymentordersuccess/",
        catalog_views.nonpaymentordersuccess,
        name="nonpaymentordersuccess",
    ),
]


urlpatterns += [
    re_path(
        r"^request_save/", request_change.request_save, name="request_save"
    ),
    re_path(
        r"^list_requests/", request_change.list_request, name="list_request"
    ),
    re_path(
        r"^view_request/", request_change.view_request, name="view_request"
    ),
    re_path(
        r"^accept_request/",
        request_change.accept_request,
        name="accept_request",
    ),
    re_path(
        r"^reject_request/",
        request_change.reject_request,
        name="reject_request",
    ),
    re_path(
        r"^permission_denied/",
        request_change.permission_denied,
        name="permission_denied",
    ),
]

src/librehatti/prints/urls.py
# -*- coding: utf-8 -*-
from django.urls import re_path
from librehatti.prints import views


app_name = "prints"

urlpatterns = [
    re_path(r"^bill/", views.bill, name="bill"),
    re_path(r"^suspense_bill/", views.suspense_bill, name="suspense_bill"),
    re_path(r"^quoted_bill/", views.quoted_bill, name="quoted_bill"),
    re_path(r"^receipt/", views.receipt, name="receipt"),
    re_path(r"^tax/", views.tax, name="tax"),
]

src/librehatti/urls.py
# -*- coding: utf-8 -*-
# from django.urls import patterns, include, url
from ajax_select import urls as ajax_select_urls
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path

from .catalog import views as catalog_views
from .prints import views as prints_views
from .programmeletter import views as programmeletter_views
from .reports import previous_history, register, views as reports_views
from .reports.register_generator import GenerateRegister
from .reports.search import SearchResult


admin.autodiscover()
urlpatterns = [
    path("api/auth/", include("djoser.urls.authtoken")),
    re_path(r"^$", catalog_views.index, name="home"),
    re_path(
        r"^catalog/",
        include(("librehatti.catalog.urls", "catalog"), namespace="catalog"),
    ),
    re_path(
        r"^useraccounts/",
        include(
            ("useraccounts.urls", "useraccounts"), namespace="useraccounts"
        ),
    ),
    re_path(
        r"^print/",
        include(("librehatti.prints.urls", "print"), namespace="print"),
    ),
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^search/", reports_views.search_form, name="search_form"),
    re_path(r"^search_result/", SearchResult.as_view(), name="search_result"),
    re_path(r"^save_fields", reports_views.save_fields, name="save_fields"),
    re_path(
        r"^list_saved_registers",
        reports_views.list_saved_registers,
        name="list_saved_registers",
    ),
    re_path(
        r"daily_result",
        register.daily_report_result,
        name="daily_report_result",
    ),
    re_path(
        r"consultancy_funds_report",
        register.consultancy_funds_report,
        name="consultancy_funds_report",
    ),
    re_path(
        r"tds_report", register.tds_report_result, name="tds_report_result"
    ),
    re_path(
        r"payment_report", register.payment_register, name="payment_register"
    ),
    re_path(
        r"suspense_clearance_register",
        register.suspense_clearance_register,
        name="suspense_clearance_register",
    ),
    re_path(
        r"servicetax", register.servicetax_register, name="servicetax_register"
    ),
    re_path(r"^main_register", register.main_register, name="main_register"),
    re_path(
        r"^proforma_register",
        register.proforma_register,
        name="proforma_register",
    ),
    re_path(
        r"^non_payment_register",
        register.non_payment_register,
        name="non_payment_register",
    ),
    re_path(
        r"^client_register", register.client_register, name="client_register"
    ),
    re_path(
        r"^material_report", register.material_report, name="material_report"
    ),
    re_path(r"^lab_report", register.lab_report, name="lab_report"),
    re_path(
        r"^suspense_register",
        register.suspense_register,
        name="suspense_register",
    ),
    re_path(
        r"^registered_users", register.registered_users, name="registered_users"
    ),
    re_path(
        r"^filter_sub_category/",
        reports_views.filter_sub_category,
        name="filter_sub_category",
    ),
    re_path(r"^bill/", prints_views.bill, name="bill"),
    re_path(
        r"^suspense_bill/", prints_views.suspense_bill, name="suspense_bill"
    ),
    re_path(r"^quoted_bill/", prints_views.quoted_bill, name="quoted_bill"),
    re_path(
        r"^bills/",
        include(("librehatti.bills.urls", "bills"), namespace="bills"),
    ),
    re_path(
        r"^suspense/",
        include(("librehatti.suspense.urls", "suspense"), namespace="suspense"),
    ),
    re_path(
        r"^generate_register/", GenerateRegister.as_view(), name="view_register"
    ),
    re_path(r"^history/", previous_history.history, name="history"),
    re_path(r"^details/", previous_history.details, name="details"),
    re_path(
        r"^proforma_details/",
        previous_history.proforma_details,
        name="proforma_details",
    ),
    re_path(r"^admin/doc/", include("django.contrib.admindocs.urls")),
    re_path(r"^admin/lookups/", include(ajax_select_urls)),
    re_path(
        r"^voucher/",
        include(("librehatti.voucher.urls", "voucher"), namespace="voucher"),
    ),
    re_path(
        r"^tinymce/", include(("tinymce.urls", "tinymce"), namespace="tinymce")
    ),
    re_path(
        r"^programmeletter/",
        programmeletter_views.programmeletter,
        name="programmeletter",
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/librehatti/voucher/urls.py
# -*- coding: utf-8 -*-
from django.urls import re_path

from . import views


urlpatterns = [
    re_path(
        r"^voucher_generate/", views.voucher_generate, name="voucher_generate"
    ),
    re_path(r"^voucher_show/", views.voucher_show, name="voucher_show"),
    re_path(r"^voucher_print/", views.voucher_print, name="voucher_print"),
]

src/librehatti/catalog/models.py
# -*- coding: utf-8 -*-
"""
models of catalog are..
"""
import datetime

import mptt.fields
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from librehatti.config import (
    BUYER,
    DELIVERY_ADDRESS,
    IS_DEBIT,
    PURCHASED_ITEMS,
    QTY,
    REFERENCE,
    REFERENCE_DATE,
)
from mptt.models import MPTTModel, TreeForeignKey
from tinymce.models import HTMLField


class FinancialSession(models.Model):
    """
    This class defines start date and end date for a financial session.
    """

    session_start_date = models.DateField()
    session_end_date = models.DateField()

    def __str__(self):
        return "%s : %s" % (self.session_start_date, self.session_end_date)


class mCategory(models.Model):
    """
    This class defines the name of category and parent category of product
    """

    name = models.CharField(max_length=100)
    parent = models.ForeignKey(
        "self", blank=True, null=True, on_delete=models.CASCADE
    )

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return str(self.name)


class Unit(models.Model):
    """
    This class defines a unit variable for Categories
    """

    unit = models.CharField(max_length=100)

    def __str__(self):
        return "%s" % (self.unit)


class Category(MPTTModel):
    """
    This class defines the name of category, its parent and unit of
    each category the organisation deals with
    """

    name = models.CharField(max_length=100)
    parent = TreeForeignKey(
        "self",
        null=True,
        blank=True,
        related_name="children",
        on_delete=models.CASCADE,
    )
    unit = models.ForeignKey(
        Unit, null=True, blank=True, on_delete=models.CASCADE
    )

    class MPTTMeta:
        order_insertion_by = ["name"]

    def __str__(self):
        return "%s" % self.name


class Product(models.Model):
    """
    This class defines the name of product, category, price of each item of
    that product and the organisation with which user deals
    """

    name = models.CharField(max_length=500)
    category = mptt.fields.TreeForeignKey(
        Category, related_name="products", on_delete=models.CASCADE
    )
    price_per_unit = models.IntegerField(blank=True, null=True)
    organisation = models.ForeignKey(
        "useraccounts.AdminOrganisations", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Attributes(models.Model):
    """
    This class defines the features of product
    """

    name = models.CharField(max_length=200)
    is_number = models.BooleanField(default=True)
    is_string = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Attributes"

    def __str__(self):
        return self.name


class ModeOfPayment(models.Model):
    """
    This class defines the details about user, its organisation, along with
    total discount and payment of job, and mode of payment
    """

    method = models.CharField(max_length=25)

    class Meta:
        verbose_name_plural = "Modes of payment"

    def __str__(self):
        return self.method


class Surcharge(models.Model):
    """
    This class defines the type of taxes, value, validation of taxes
    mentioning the startdate and end date
    """

    tax_name = models.CharField(max_length=200)
    value = models.FloatField()
    taxes_included = models.BooleanField(default=False)
    tax_effected_from = models.DateField(null=True)
    tax_valid_till = models.DateField(null=True)
    Remark = models.CharField(max_length=1000, null=True)

    def __str__(self):
        return self.tax_name


class PurchaseOrder(models.Model):
    """
    This class defines members for orders to placed by users
    """

    buyer = models.ForeignKey(
        User, verbose_name=BUYER, on_delete=models.CASCADE
    )
    is_debit = models.BooleanField(default=False, verbose_name=IS_DEBIT)
    reference = models.CharField(max_length=200, verbose_name=REFERENCE)
    reference_date = models.DateField(
        blank=True, null=True, verbose_name=REFERENCE_DATE
    )
    delivery_address = models.CharField(
        max_length=500, blank=True, null=True, verbose_name=DELIVERY_ADDRESS
    )
    organisation = models.ForeignKey(
        "useraccounts.AdminOrganisations", default=1, on_delete=models.CASCADE
    )
    date_time = models.DateField(auto_now_add=True)
    purchase_order_time = models.TimeField(auto_now_add=True)
    total_discount = models.IntegerField(default=0)
    tds = models.IntegerField(default=0)
    mode_of_payment = models.ForeignKey(ModeOfPayment, on_delete=models.CASCADE)
    cheque_dd_number = models.CharField(max_length=50, blank=True)
    cheque_dd_date = models.DateField(max_length=50, blank=True, null=True)
    type_of_service = models.ForeignKey(
        "useraccounts.OrganisationType", on_delete=models.CASCADE
    )
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        surchages = Surcharge.objects.filter(taxes_included=1)

        if surchages:
            pass
        else:
            raise ValidationError("No Active Taxes. Unable to add Order")
        now = datetime.datetime.now()
        financialsession = FinancialSession.objects.values(
            "id", "session_start_date", "session_end_date"
        )
        for value in financialsession:
            start_date = value["session_start_date"]
            end_date = value["session_end_date"]
            if start_date <= now.date() <= end_date:
                session_id = value["id"]
        try:
            session_id
            super(PurchaseOrder, self).save(*args, **kwargs)
        except BaseException:
            raise ValidationError("No Current Financial Session")

    def __str__(self):
        return "%s" % (self.id)


class PurchasedItem(models.Model):
    """
    This class defines members for items purchased in a purchase order
    """

    purchase_order = models.ForeignKey(PurchaseOrder, on_delete=models.CASCADE)
    price_per_unit = models.IntegerField()
    qty = models.IntegerField(verbose_name=QTY)
    price = models.IntegerField()
    item = models.ForeignKey(Product, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        try:
            if self.purchase_order:
                self.price = self.price_per_unit * self.qty
                super(PurchasedItem, self).save(*args, **kwargs)
        except BaseException:
            raise ValidationError("No Active Taxes. Unable to add Items")

    def __str__(self):
        return "%s" % (self.item) + " - " "%s" % (self.purchase_order)

    class Meta:
        verbose_name = PURCHASED_ITEMS
        verbose_name_plural = PURCHASED_ITEMS


class Catalog(models.Model):
    """
    This class defines the features, value of product
    """

    attribute = models.ForeignKey(Attributes, on_delete=models.CASCADE)
    value = models.CharField(max_length=200)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return self.attribute.name


class TaxesApplied(models.Model):
    """
    This class defines the taxes applied on the purchase order
    """

    purchase_order = models.ForeignKey(PurchaseOrder, on_delete=models.CASCADE)
    surcharge = models.ForeignKey(Surcharge, on_delete=models.CASCADE)
    surcharge_name = models.CharField(max_length=500)
    surcharge_value = models.FloatField()
    tax = models.IntegerField()

    def __str__(self):
        return "%s" % (self.surcharge)


class Bill(models.Model):
    """
    This class defines the grand total of the purchase order
    """

    purchase_order = models.ForeignKey(PurchaseOrder, on_delete=models.CASCADE)
    delivery_charges = models.IntegerField()
    total_cost = models.IntegerField()
    totalplusdelivery = models.IntegerField()
    total_tax = models.IntegerField()
    grand_total = models.IntegerField()
    amount_received = models.IntegerField()


class HeaderFooter(models.Model):
    """
    This class is used to add, edit or delete Header and Footer to be
    used for Bills in the organisation
    """

    header = HTMLField()
    footer = HTMLField()
    is_active = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.is_active:
            temp = HeaderFooter.objects.filter(is_active=1)
            if temp:
                HeaderFooter.objects.filter(is_active=1).update(is_active=0)
                super(HeaderFooter, self).save(*args, **kwargs)
            else:
                super(HeaderFooter, self).save(*args, **kwargs)
        else:
            super(HeaderFooter, self).save(*args, **kwargs)

    def __str__(self):
        return "%s" % (self.id)

    class Meta:
        verbose_name_plural = "Header and Footer"


class SurchargePaid(models.Model):
    surcharge = models.ForeignKey(Surcharge, on_delete=models.CASCADE)
    value = models.IntegerField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return "%s paid on %s" % (self.surcharge, self.date)


class ChangeRequest(models.Model):
    """
    This class defines members which enables the user to select a purchase order
    to request a change in the Bill Amount
    """

    purchase_order_of_session = models.IntegerField()
    session = models.ForeignKey(FinancialSession, on_delete=models.CASCADE)
    previous_total = models.IntegerField()
    new_total = models.IntegerField()
    description = models.CharField(max_length=100)
    initiator = models.CharField(max_length=50)
    initiation_date = models.DateField(auto_now_add=True)


class RequestSurchargeChange(models.Model):
    """
    This class defines members for requesting the change in a Bill
    """

    change_request = models.ForeignKey(ChangeRequest, on_delete=models.CASCADE)
    surcharge = models.ForeignKey(TaxesApplied, on_delete=models.CASCADE)

src/templates/catalog/change_form.html
{% extends 'base.html' %}
{% load i18n %} {% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
   {% block title %}
   <title>Change Request</title>
   {% endblock %}
</head>
<body>
  {% block content %}
  {% if messages %}
                <div class="alert alert-success">
                    <p>{{ messages }}</p>
                </div>
                {% endif %}
  <div class='change_request'>
    <table>
       <tr>
          <th>Client:</th>
          <td>{{details.purchase_order__buyer__first_name}}&nbsp;{{details.purchase_order__buyer__last_name}}
           &nbsp;{{details.purchase_order__buyer__customer__title}}</td>
       </tr>
       <tr>
           <th>Address:</th>
           <td>{{details.purchase_order__buyer__customer__address__street_address}}&nbsp;
              {{details.purchase_order__buyer__customer__address__district}}</td>
          </tr>
          <tr>
           <th>Mode Of Payment:</th>
           <td>{{details.purchase_order__mode_of_payment__method}}</td>
       </tr>
   </table>
</div>
<table>
    <tr>
        <td>
        </td>
    </tr>
</table>
<form action='{% url 'catalog:request_save' %}?order_id={{order_id}}&session={{session}}' method='POST'>
    <table class="changeform">
        {% csrf_token %}
        <tr>
            <th><label>Previous Total:</label></th>
            <th><input name="previous_total" class='form-control' value="{{bill.grand_total}}" readonly="readonly" type="text"
                id="previous_total" /></th>
            </tr>
            <tr>
                <th><label>Surcharge:</label></th>
                <th><label>Previous:</label></th>
                <th><label>New:</label></th>
            </tr>
            {% for value in surcharge %}
            <tr>
                <td><input name="surcharge" class='form-control' value="{{value.surcharge__tax_name}}" readonly="readonly" type="text" /></td>
                <td><input name="previous_value" class='form-control' value="{{value.tax}}" readonly="readonly" type="text" id="previous_{{value.id}}" /></td>
                <td><input name="new_value" type="number" class='form-control new_value' placeholder="New Value" id="{{value.id}}" /></td>
            </tr>
            {% endfor %}
            <tr>
                <th><label>New Total:</label></th>
                <th><input name="new_total" class='form-control' readonly="readonly" type="text" id="new_total" /></th>
            </tr>
        </table>
        <label for="id_description">Description:</label>
        <textarea cols="40" name="description" rows="5" placeholder="Description"></textarea>
        <input type="submit" class="btn btn-info btn-large" value="Send Request" name='button1' id='button1' />
    </form>
    {% endblock %}
</body>
</html>

src/templates/catalog/change_request.html
{% extends "base.html" %} {% load static %}
<html>
<head>
    {% block title %}
    <title>Form</title>
    {% endblock %}
</head>
<body>
    {% block content %}
    <form method="POST" action={% url 'catalog:change_request' %} >
        {% if errors %}
        <div class="alert alert-danger">
            {{ errors }}
        </div>
        {% endif %}
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit" class="btn btn-info btn-large" value="Submit" id="button1">
    </form>
    {% endblock %}
</body>
</html>

src/templates/catalog/form.html
<html>

    <head>
        <style type="text/css">
            span.s1{margin-left: 9%;}
            span.s2{margin-left: 8%;}
    	    span.s3{margin-left: 10%;}
    	    span.sm{margin-left: 4%;}
        </style>
        <title>Transport</title>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                function updateElementIndex(el, prefix, ndx) {
	                var id_regex = new RegExp('(' + prefix + '-\\d+-)');
    	            var replacement = prefix + '-' + ndx + '-';
    	            if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
    	            if (el.id) el.id = el.id.replace(id_regex, replacement);
    	            if (el.name) el.name = el.name.replace(id_regex, replacement);
    	        }
             

    	        function addForm(btn, prefix) {
    	            var formCount = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
	
    	            // You can only submit a maximum of 30 todo items 
    	            if (formCount < 30) {
    		  		    // Clone a form (without event handlers) from the first form
    		  		    var row = $(".item:first").clone(false).get(0);
    		 		    // Insert it after the last form
    		            $(row).removeAttr('id').hide().insertAfter(".item:last").slideDown(300);
      
				        // Remove the bits we don't want in the new row/form
    		 		    // e.g. error messages
    		  		    $(".errorlist", row).remove();
    		  		    $(row).children().removeClass('error');
    		  
				        // Relabel/rename all the relevant bits
    		  			$(row).children().children().each(function() {
    		    		    updateElementIndex(this, prefix, formCount);
    		    			if ( $(this).attr('type') == 'text' )
    			   		    	$(this).val('');
    		  			});
      
			        	// Add an event handler for the delete item/form link 
    		 	    	$(row).find('.delete').click(function() {
    		   		    	return deleteForm(this, prefix);
    		  			});
		
    		        	// Update the total form count
    		  			$('#id_' + prefix + '-TOTAL_FORMS').val(formCount + 1); 
		
			    	} // End if

    				else 
					{
      					alert("Sorry, you can only enter a maximum of 30 items.");
    				}
    				return false;
      			}

  				// Register the click event handlers
  				$("#add").click(function() {
    				return addForm(this, 'form');
  				});
            });
        </script>
   
    </head>
    

    <body class= "transport">

        <form  action="/catalog/transp/" method="POST">{% csrf_token %}
            <div id="frm">
                {{TransportFormA.as_p}}
                {{ transport_formset.management_form }}
                {% for form in todo_item_formset.forms %}
                <div class="item">
                    {{TransportFormB.as_p}}
                </div>  
                {% endfor %}      
            </div>
            <input type="submit" value="Generate Bill" name="button1" > 
            <a id= "add" href="#"><input type="button" value="Add Another" name="button2"></a>
         </form>
            
    </body>

</html>

src/templates/catalog/list_products.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Products</title>
    {% load static %}
    <link href="{% static 'css/product_list.css' %}" media="all" rel="stylesheet" type="text/css">
</head>
<body>

    <div class = "wrapper">
        <h2 class="parent-category"> {{root_name.name}} </h2>
        {% for result in result %}
        <div class="products-list">
            <h2 class="parent-category"> {{ result.0 }} </h2>
            {% for category in result.1 %}
            <h4>{{ category.name }}</h4>
            <div class="product-container">
                {% for product in result.2 %}
                {% if product.category_id == category.id %}
                <h4 class="product-head"> <span class="product-name"> {{ product.name | safe}} </span>
                    <span class="product-price">&#8377; {{ product.price_per_unit }}/- </span> </h4>

                    {% endif %}
                    {% endfor %}
                </div>
                {% endfor %}
            </div>
            {% endfor %}
        </div>
    </body>
    </html>

src/templates/catalog/list_request.html
{% extends 'base_register.html' %}
{% load i18n %} {% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
    <title>
        Requests
    </title>
    {% endblock %}
</head>
<body>
{% block content %}
<div class = 'list-registers'>
    <div class='view-list'>
        <table border='1px'>
            <tr>
                <th>Request Id</th>
                <th>Description</th>
                <th>Status</th>
                <th>Option</th>
            </tr>
            {% for values in list %}
            <tr>
                <td>{{values.id}}</td>
                <td>{{values.description}}</td>
                <td>{{values.request_status}}</td>
                <td><a href = '{% url 'catalog:view_request' %}?id={{values.id}}'>View</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}
</body>
</html>

src/templates/catalog/order_added_success.html
{% extends 'base_register.html' %}
{% load i18n %} {% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
   {% block title %}
   <title>Order added</title>
   {% endblock %}
</head>
<body>
  {% block content %}
  <div class='order-success'>
   <p class='success-message'>Order added <span class='green'>
      Successfully</span></p>
      <table>
       <tr>
          <th>Client:</th>
          <td>{{details.purchase_order__buyer__first_name}}&nbsp;{{details.purchase_order__buyer__last_name}}
           &nbsp;{{details.purchase_order__buyer__customer__title}}</td>
       </tr>
       <tr>
           <th>Address:</th>
           <td>{{details.purchase_order__buyer__customer__address__street_address}}&nbsp;
              {{details.purchase_order__buyer__customer__address__district}}</td>
          </tr>
          <tr>
           <th>Mode Of Payment:</th>
           <td>{{details.purchase_order__mode_of_payment__method}}</td>
       </tr>
   </table>
   <div class='order-success-options'>
    <table>
        <tr>
           <th colspan='3'><h3>Options</h3></th>
       </tr>
       <tr>
          {% if details.receipt_no_of_session %}
           <td><a target="_blank" href = '{% url 'prints:receipt' %}?order_id={{order_id}}'><input type="button" class="btn btn-info btn-large" name="" value="Receipt"></a></td>
           {% else %}
           <td><a target="_blank" href = '{% url 'prints:receipt' %}?order_id={{order_id}}'><input type="button" class="btn btn-info btn-large" name="" value="Confirm"></a></td>
           {% endif %}
           <td></td>
           <td><a target="_blank" href = '{% url 'voucher:voucher_show' %}?order_id={{order_id}}'><input type="button" class="btn btn-info btn-large" name="" value="Voucher"></a></td>
       </tr>
       <tr>
           <td><a target="_blank" href = '{% url 'prints:bill' %}?order_id={{order_id}}'><input type="button" class="btn btn-info btn-large" name="" value="Bill"></a></td>
           <td></td>
           <td><a target="_blank" href = '{% url 'prints:tax' %}?order_id={{order_id}}'><input type="button" class="btn btn-info btn-large" name="" value="Tax Details"></a></td>
       </tr>
       {% if suspense_flag == 1 %}
       <tr>
           <td></td>
           <td><a target="_blank" href = '{% url 'prints:suspense_bill' %}?order_id={{order_id}}'><input type="button" class="btn btn-info btn-large" name="" value="Suspense Bill"></a></td>
           <td></td>
       </tr>
       {% endif %}
           </table>
       </div>
   </div>
   {% endblock %}
</body>
</html>

src/templates/catalog/product_list_form.html
{% extends "base.html" %}
{% load i18n %} {% load static %}

<html>
<head>
{% block title %}
<title>Form</title>
{% endblock %}
</head>
<body>
  {% block content %}
  <form class="form-horizontal" role="form" method="POST"  action="{% url 'catalog:list_products' %}">
  	<div class="form-group">
       	{% csrf_token %}
       		<table class="form_class">
            {{form.as_table}}
          </table>
   	      <input type="submit" class="btn btn-info btn-large" value="Submit" name='button1' id='button1'>
 	</div>
</form>
   {% endblock %}
 </body>
 </html>