src/librehatti/bills/urls.py
# -*- coding: utf-8 -*-
from django.urls import re_path
from librehatti.bills import views


urlpatterns = [
    re_path(
        r"^quoted_bill_cal/", views.quoted_bill_cal, name="quoted_bill_cal"
    ),
    re_path(
        r"^quoted_order_added_success/",
        views.quoted_order_added_success,
        name="quoted_order_added_success",
    ),
    re_path(r"^select_note/", views.select_note, name="select_note"),
    re_path(
        r"^select_note_save/", views.select_note_save, name="select_note_save"
    ),
    re_path(r"^new_note_line/", views.new_note_line, name="new_note_line"),
    re_path(r"^delete_note/", views.delete_note, name="delete_note"),
    re_path(
        r"^quoted_order_of_session/",
        views.quoted_order_of_session,
        name="quoted_order_of_session",
    ),
]

src/librehatti/prints/urls.py
# -*- coding: utf-8 -*-
from django.urls import re_path
from librehatti.prints import views


app_name = "prints"

urlpatterns = [
    re_path(r"^bill/", views.bill, name="bill"),
    re_path(r"^suspense_bill/", views.suspense_bill, name="suspense_bill"),
    re_path(r"^quoted_bill/", views.quoted_bill, name="quoted_bill"),
    re_path(r"^receipt/", views.receipt, name="receipt"),
    re_path(r"^tax/", views.tax, name="tax"),
]

src/librehatti/urls.py
# -*- coding: utf-8 -*-
# from django.urls import patterns, include, url
from ajax_select import urls as ajax_select_urls
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path

from .catalog import views as catalog_views
from .prints import views as prints_views
from .programmeletter import views as programmeletter_views
from .reports import previous_history, register, views as reports_views
from .reports.register_generator import GenerateRegister
from .reports.search import SearchResult


admin.autodiscover()
urlpatterns = [
    path("api/auth/", include("djoser.urls.authtoken")),
    re_path(r"^$", catalog_views.index, name="home"),
    re_path(
        r"^catalog/",
        include(("librehatti.catalog.urls", "catalog"), namespace="catalog"),
    ),
    re_path(
        r"^useraccounts/",
        include(
            ("useraccounts.urls", "useraccounts"), namespace="useraccounts"
        ),
    ),
    re_path(
        r"^print/",
        include(("librehatti.prints.urls", "print"), namespace="print"),
    ),
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^search/", reports_views.search_form, name="search_form"),
    re_path(r"^search_result/", SearchResult.as_view(), name="search_result"),
    re_path(r"^save_fields", reports_views.save_fields, name="save_fields"),
    re_path(
        r"^list_saved_registers",
        reports_views.list_saved_registers,
        name="list_saved_registers",
    ),
    re_path(
        r"daily_result",
        register.daily_report_result,
        name="daily_report_result",
    ),
    re_path(
        r"consultancy_funds_report",
        register.consultancy_funds_report,
        name="consultancy_funds_report",
    ),
    re_path(
        r"tds_report", register.tds_report_result, name="tds_report_result"
    ),
    re_path(
        r"payment_report", register.payment_register, name="payment_register"
    ),
    re_path(
        r"suspense_clearance_register",
        register.suspense_clearance_register,
        name="suspense_clearance_register",
    ),
    re_path(
        r"servicetax", register.servicetax_register, name="servicetax_register"
    ),
    re_path(r"^main_register", register.main_register, name="main_register"),
    re_path(
        r"^proforma_register",
        register.proforma_register,
        name="proforma_register",
    ),
    re_path(
        r"^non_payment_register",
        register.non_payment_register,
        name="non_payment_register",
    ),
    re_path(
        r"^client_register", register.client_register, name="client_register"
    ),
    re_path(
        r"^material_report", register.material_report, name="material_report"
    ),
    re_path(r"^lab_report", register.lab_report, name="lab_report"),
    re_path(
        r"^suspense_register",
        register.suspense_register,
        name="suspense_register",
    ),
    re_path(
        r"^registered_users", register.registered_users, name="registered_users"
    ),
    re_path(
        r"^filter_sub_category/",
        reports_views.filter_sub_category,
        name="filter_sub_category",
    ),
    re_path(r"^bill/", prints_views.bill, name="bill"),
    re_path(
        r"^suspense_bill/", prints_views.suspense_bill, name="suspense_bill"
    ),
    re_path(r"^quoted_bill/", prints_views.quoted_bill, name="quoted_bill"),
    re_path(
        r"^bills/",
        include(("librehatti.bills.urls", "bills"), namespace="bills"),
    ),
    re_path(
        r"^suspense/",
        include(("librehatti.suspense.urls", "suspense"), namespace="suspense"),
    ),
    re_path(
        r"^generate_register/", GenerateRegister.as_view(), name="view_register"
    ),
    re_path(r"^history/", previous_history.history, name="history"),
    re_path(r"^details/", previous_history.details, name="details"),
    re_path(
        r"^proforma_details/",
        previous_history.proforma_details,
        name="proforma_details",
    ),
    re_path(r"^admin/doc/", include("django.contrib.admindocs.urls")),
    re_path(r"^admin/lookups/", include(ajax_select_urls)),
    re_path(
        r"^voucher/",
        include(("librehatti.voucher.urls", "voucher"), namespace="voucher"),
    ),
    re_path(
        r"^tinymce/", include(("tinymce.urls", "tinymce"), namespace="tinymce")
    ),
    re_path(
        r"^programmeletter/",
        programmeletter_views.programmeletter,
        name="programmeletter",
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/librehatti/bills/forms.py
# -*- coding: utf-8 -*-

from ajax_select import make_ajax_field
from django import forms
from librehatti.bills.models import NoteLine, QuotedOrder
from librehatti.catalog.models import Category, Product
from librehatti.config import ITEM, PARENT_CATEGORY, SUB_CATEGORY, TYPE
from librehatti.constants import ITEM_SELECT_CHOICES


class BuyerForm(forms.ModelForm):
    """
    Buyer form for quoted order.
    """

    buyer = make_ajax_field(QuotedOrder, "buyer", "buyer")

    class Meta:
        model = QuotedOrder
        exclude = ("is_active",)

    class Media:
        js = ("js/hide_add_buyer.js", "js/cheque_dd_date.js")


class ItemSelectForm(forms.ModelForm):
    """
    This form lets user to select item after categories are
    filtered in dropdown.
    """

    class Media:
        js = ("js/quote_ajax.js", "js/quoted_price_per_unit.js")

    try:
        parent_category = forms.ModelChoiceField(
            queryset=Category.objects.filter(
                parent__parent__isnull=True
            ).filter(parent__isnull=False),
            label=PARENT_CATEGORY,
        )
        sub_category = forms.ModelChoiceField(
            queryset=Category.objects.all(), label=SUB_CATEGORY
        )
    except BaseException:
        raise

    item = forms.ModelChoiceField(queryset=Product.objects.all(), label=ITEM)
    type = forms.ChoiceField(choices=ITEM_SELECT_CHOICES, label=TYPE)
    price_per_unit = forms.IntegerField()

    def __init__(self, *args, **kwargs):
        super(ItemSelectForm, self).__init__(*args, **kwargs)
        self.fields["type"].widget.attrs = {"class": "type"}
        self.fields["parent_category"].widget.attrs = {
            "class": "parent_category"
        }
        self.fields["sub_category"].widget.attrs = {"class": "sub_category"}
        self.fields["item"].widget.attrs = {"class": "item"}
        self.fields["price_per_unit"].widget.attrs = {
            "class": "quoted_price_per_unit"
        }


class SelectNoteForm(forms.Form):
    """
    Form for selection of note line while adding note line.
    """

    quoted_order = forms.CharField(
        widget=forms.TextInput(attrs={"readonly": "readonly"})
    )
    note_line = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(attrs={"class": "note_checkbox"}),
        queryset=NoteLine.objects.filter(is_permanent=0),
    )

src/librehatti/bills/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.db.models import Max, Sum
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from librehatti.bills.forms import SelectNoteForm
from librehatti.bills.models import (
    NoteLine,
    QuotedBill,
    QuotedItem,
    QuotedOrder,
    QuotedOrderNote,
    QuotedOrderofSession,
    QuotedTaxesApplied,
)
from librehatti.catalog.models import SpecialCategories, Surcharge
from librehatti.catalog.request_change import request_notify
from librehatti.suspense.models import QuotedSuspenseOrder
from librehatti.voucher.models import FinancialSession


@login_required
def quoted_bill_cal(request):
    """
    This view calculate taxes on quoted order, bill data
    and save those values in database.
    argument: Http request
    returns: Redirects to select option page after calculations.
    """
    old_post = request.session.get("old_post")
    quoted_order_id = request.session.get("quoted_order_id")
    generate_tax = 1
    first_item = QuotedItem.objects.values("item__category__id").filter(
        quoted_order=quoted_order_id
    )[0]
    category_check = SpecialCategories.objects.filter(
        category=first_item["item__category__id"]
    )
    if category_check:
        specialcategories = SpecialCategories.objects.values("tax").filter(
            category=first_item["item__category__id"]
        )[0]
        if not specialcategories["tax"]:
            generate_tax = 0
    quoted_order = QuotedOrder.objects.get(id=quoted_order_id)
    quoted_order_obj = QuotedOrder.objects.values("total_discount").get(
        id=quoted_order_id
    )
    quoted_item = QuotedItem.objects.filter(
        quoted_order=quoted_order_id
    ).aggregate(Sum("price"))
    total = quoted_item["price__sum"]
    price_total = total - quoted_order_obj["total_discount"]
    totalplusdelivery = price_total
    surcharge = Surcharge.objects.values(
        "id", "value", "taxes_included", "tax_name"
    )
    delivery_rate = Surcharge.objects.values("value").filter(
        tax_name="Transportation"
    )
    distance = QuotedSuspenseOrder.objects.filter(
        quoted_order=quoted_order_id
    ).aggregate(Sum("distance_estimated"))
    if distance["distance_estimated__sum"]:
        delivery_charges = (
            int(distance["distance_estimated__sum"]) * delivery_rate[0]["value"]
        )
        totalplusdelivery = totalplusdelivery + delivery_charges

    else:
        delivery_charges = 0

    for value in surcharge:
        surcharge_id = value["id"]
        surcharge_val = value["value"]
        surcharge_tax = value["taxes_included"]
        if surcharge_tax == 1 and generate_tax == 1:
            taxes = round((totalplusdelivery * surcharge_val) / 100)
            surcharge_obj = Surcharge.objects.get(id=surcharge_id)
            taxes_applied = QuotedTaxesApplied(
                quoted_order=quoted_order,
                surcharge=surcharge_obj,
                tax=taxes,
                surcharge_name=value["tax_name"],
                surcharge_value=value["value"],
            )
            taxes_applied.save()
    taxes_applied_temp = QuotedTaxesApplied.objects.filter(
        quoted_order=quoted_order_id
    )
    if taxes_applied_temp:
        taxes_applied_obj = QuotedTaxesApplied.objects.filter(
            quoted_order=quoted_order_id
        ).aggregate(Sum("tax"))
        tax_total = taxes_applied_obj["tax__sum"]
    else:
        tax_total = 0
    grand_total = price_total + tax_total + delivery_charges
    amount_received = grand_total
    bill = QuotedBill(
        quoted_order=quoted_order,
        total_cost=price_total,
        total_tax=tax_total,
        grand_total=grand_total,
        delivery_charges=delivery_charges,
        amount_received=amount_received,
        totalplusdelivery=totalplusdelivery,
    )
    bill.save()
    request.session["old_post"] = old_post
    request.session["quoted_order_id"] = quoted_order_id
    return HttpResponseRedirect(reverse("bills:select_note"))


@login_required
def quoted_order_added_success(request):
    """
    View to handle success of addition of quoted order.
    argument: Http request
    returns: Render success page after adding quoted order.
    """
    quoted_order_id = request.session.get("quoted_order_id")
    details = QuotedOrder.objects.values(
        "buyer__first_name",
        "buyer__last_name",
        "buyer__customer__address__street_address",
        "buyer__customer__title",
        "buyer__customer__address__district",
    ).filter(id=quoted_order_id)[0]
    return render(
        request,
        "bills/quoted_success.html",
        {"details": details, "quoted_order_id": quoted_order_id},
    )


@login_required
def select_note(request):
    """
    View to handle selection of extra notes while adding quoted order.
    argument: Http Request.
    returns: Render form for selection of note form.
    """
    quoted_order_id = request.session.get("quoted_order_id")
    form = SelectNoteForm(initial={"quoted_order": quoted_order_id})
    request_status = request_notify()
    return render(
        request,
        "bills/select_note.html",
        {"form": form, "request": request_status},
    )


@login_required
def select_note_save(request):
    """
    View to hanle saving of selected note in quoted order.
    argument: Http Request
    returns: Redirects to success page after selection of note line.
    """
    if request.method == "POST":
        form = SelectNoteForm(request.POST)
        if form.is_valid():
            formdata = form.cleaned_data
            quoted_order = formdata["quoted_order"]
            quoted_order_id = QuotedOrder.objects.get(id=quoted_order)
            note_list = []
            for note in formdata["note_line"]:
                note_list.append(note)
            for value in note_list:
                obj = QuotedOrderNote(quoted_order=quoted_order_id, note=value)
                obj.save()

            return HttpResponseRedirect(
                reverse("bills:quoted_order_added_success")
            )
        else:
            return HttpResponseRedirect(
                reverse("bills:quoted_order_added_success")
            )
    else:
        error_type = "404 Forbidden"
        error = "Please again place the order"
        temp = {"type": error_type, "message": error}
        return render(request, "error_page.html", temp)


@login_required
def new_note_line(request):
    """
    It hanles addition of new condition line.
    argument: Http Request
    """
    note_line = request.GET["note_line"]
    obj = NoteLine(note=note_line)
    obj.save()
    return HttpResponse("")


@login_required
def delete_note(request):
    """
    It handles deletion of condition line.
    argument: Http Request.
    """
    delete_note = request.GET["delete_note"]
    delete_note_id = delete_note.split(",")
    for id in delete_note_id:
        NoteLine.objects.filter(id=id).delete()
    return HttpResponse("")


@login_required
def quoted_order_of_session(request):
    """
    It handles financial sessions for quoted order.
    argument: Http Request
    returns: Redirects to function for adding quoted add distance.
    """
    old_post = request.session.get("old_post")
    quoted_order_id = request.session.get("quoted_order_id")
    quoted_order = QuotedOrder.objects.get(id=quoted_order_id)
    quoted_order_obj = QuotedOrder.objects.values("id", "date_time").get(
        id=quoted_order_id
    )
    quoted_order_date = quoted_order_obj["date_time"]
    financialsession = FinancialSession.objects.values(
        "id", "session_start_date", "session_end_date"
    )
    for value in financialsession:
        start_date = value["session_start_date"]
        end_date = value["session_end_date"]
        if start_date <= quoted_order_date <= end_date:
            session_id = value["id"]
    session = FinancialSession.objects.get(id=session_id)
    max_id = QuotedOrderofSession.objects.all().aggregate(Max("id"))
    if max_id["id__max"] is None:
        obj = QuotedOrderofSession(
            quoted_order=quoted_order, session=session, quoted_order_session=1
        )
        obj.save()
    else:
        quoted_order_of_session = QuotedOrderofSession.objects.values(
            "quoted_order_session", "session"
        ).get(id=max_id["id__max"])
        if quoted_order_of_session["session"] == session_id:
            obj = QuotedOrderofSession(
                quoted_order=quoted_order,
                session=session,
                quoted_order_session=quoted_order_of_session[
                    "quoted_order_session"
                ]
                + 1,
            )
            obj.save()
        else:
            obj = QuotedOrderofSession(
                quoted_order=quoted_order,
                session=session,
                quoted_order_session=1,
            )
            obj.save()
    request.session["old_post"] = old_post
    request.session["quoted_order_id"] = quoted_order_id
    return HttpResponseRedirect(reverse("suspense:quoted_add_distance"))

src/templates/bills/quote .html
<html>
<head>
 
	<meta http-equiv="refresh" content="15">
	<style type="text/css">
	h1{margin-left: 30%;}
	h1.as{margin-left: 35%;} 
 
	
	 	table{width: 60%; margin-left:15%;}	
		th{padding:10px;}
		td{padding-left:40px;
			padding-top: 25px;
		    padding-bottom: 25px;}
 
		p.bs{margin-left: 25%;}
		
	</style>
 
<title>Quotes</title>  
</head>
 
 
<body>
 
<h1>Guru Nanak Dev Engineering College</h1>
<h1 class='as'>Testing and Consultancy</h1>
 
<p class="bs"><center> Website:http//tcc.gndec.ac.in &nbsp;&nbsp;&nbsp; 
                              &nbsp;&nbsp;&nbsp;&nbsp;Email:tcc@gndec.ac.in<br>
                              <br>Ph:0161-2491193,5064509 &nbsp;&nbsp;&nbsp;
                              &nbsp;&nbsp;&nbsp;&nbsp;Fax:0161-5064742 </center>
                              </p>
 
 
<br>
<br>
<br>
<br>
<br>
	<table border="1" >
	<tr>
 		<th> Client </th>
		<th> Address </th>
		<th> unknown </th>
                <th> unknown </th>
		<th> Produce</th>
		
	</tr>
{% for m in QuotedOrder_list %}
        <tr>
		<td> {{m.quote_buyer_id.username}}</td>
		<td> {{m.quote_delivery_address}}</td>
		<td> {{m.}}</td>
                <td> {{m.}}</td>
		<td>
		<a href="/bills/generateproforma/{{m.id}}" style="text-decoration:none">
                <input type="submit" value="Generate Proforma" name="Generate Proforma">
		</a>
			<br>
		<a href="/bills/confirm/{{m.id}}">
			<input type="submit" value="Confirm" name="Confirm">
		</a>
		</td>
    </tr>
    {% endfor %}
</table>
 
</body>
</html>

src/templates/bills/quote_bill.html
{% extends 'bill_base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset='UTF-8'>
    {% block title %}
    <title>Proforma Bill</title>
    {% endblock %}
    {% load set_var %}
</head>
<body>
    {% block content %}
    <div class = "bill-left">
        <span id ="highlight">GST IN: </span>{{ admin_org.gst_in }}
        <span id = "dated"><span id ="highlight">PAN No. </span>{{ admin_org.pan_no }}</span>
    </div>
    <div class="container">
        <h2>Proforma Bill</h2>
    </div>
    <div class = "bill-left">
        <div><span id ="highlight">No. </span>GNDEC/TCC/B/{{quoted_order_id}} <span id = "dated"><span id ="highlight">Dated : </span>{{ date|date:"d M, Y" }}</span></div>
        <p> To </p>
        <div>
        {% if buyer.buyer__first_name %}
        {{buyer.buyer__first_name}} {{buyer.buyer__last_name}}
        {% else %}
        {{buyer.buyer__customer__title}}
        {% endif %},</div>
        <div>{{address.address__street_address}}, </div>
        <div>{{address.address__district}}
            {% if address.address__pin != 'None' and address.address__pin != '' %}
            -{{address.address__pin}}
            {% endif %},</div>
        <div>{{address.address__province}}</div>
        {% if buyer_name.company %}
        <div><b>Agency:</b> {{buyer_name.company}}</div>
        {% endif %}
            <p><span id ="highlight"> Ref: </span>{{ref_letter}} {{ref.reference}} dated {{ref.reference_date}}</p>
            <p><span id ="highlight"> Site: </span>{{site.delivery_address}}</p>
        </div>
        <table class="data" border="1px">
            <tr>
                <th>Item/Services</th>
                <th>Quantity/Unit</th>
                <th>Rate &#8377;</th>
                <th>Total &#8377;</th>
            </tr>
            <tr>
                {% for bill_values in bill_values %}
                <td>
                    {{bill_values.0}}
                    {%for value in bill_values.1%}
                    {{value}}
                    {% endfor %}
                </td>
                <td>
                    {%for value in bill_values.2%}
                    {% if not forloop.last %}
                    {{value}}
                    {% endif %}
                    {% if value == 'no_unit' and forloop.last %}
                    sample/s
                    {% elif value != 'no_unit' and forloop.last %}
                    {{value}}
                    {% endif %}
                    {% endfor %}
                </td>
                <td>
                    {%for value in bill_values.3%}
                    {{value}}
                    {% endfor %}
                </td>
                <td id="total">
                    {{bill_values.4}}
                </td>
            </tr>
            {% endfor %}
            {% if total_discount %}
            <tr>
                <td>Discount</td>
                <td colspan="2" rowspan="{{tax_count}}"></td>
                <td id="total">{{total_discount}}</td>
            </tr>
            {% endif %}
            <tr>
                <td><b>Total </b></td>
                {% if total_discount %}
                {% else %}
                <td  colspan="2" rowspan="{{tax_count}}"></td>
                {% endif %}
                <td id="total"><b>{{total_cost}}</b></td>
            </tr>
            {% if delivery_charges != 0 %}
            <tr>
                <td>Transportation & Other Charges</td>
                <td id="total">{{delivery_charges}}</td>
            </tr>
            <tr>
                <td>Total Amount</td>
                <td id="total">{{totalplusdelivery}}</td>
            </tr>
            {% endif %}
            <tr>
                {% if taxes_applied %}
                {% for taxesapplied in taxes_applied %}
                <td> {{ taxesapplied.surcharge_name }} @ {{ taxesapplied.surcharge_value }} % </td>
                <td id="total">  {{taxesapplied.tax }} </td>
            </tr>
            {% endfor %}
            {% endif %}
            <tr>
                <td><b>Total &#8377; </b>({{total_in_words}} only)</td>
                <td id="total"><b>{{grand_cost}}</b></td>
            </tr>
        </table>
        <div>
            <div class="position">
                <b>Terms & Conditions:</b>
            </div>
            <div style="clear:both;">
            </div>
            <div id="notelist">
                <ol>
                    {% for value in permanent_note %}
                    <li>{{value.note}}</li>
                    {% endfor %}
                    {% for value in quoted_note %}
                    <li>{{value.note}}</li>
                    {% endfor %}
                    <li>Bank Details For RTGS Payment:</li>
                </ol>
            </div>
            <div id="account">
                <table>
                    <tr>
                        <td>Acount Holder</td>
                        <td>:</td>
                        <td>{{account_holder}}</td>
                    </tr>
                    <tr>
                        <td>Name of Bank</td>
                        <td>:</td>
                        <td>{{name_of_bank}}</td>
                    </tr>
                    <tr>
                        <td>Branch</td>
                        <td>:</td>
                        <td>{{branch}}</td>
                    </tr>
                    <tr>
                        <td>Account No.</td>
                        <td>:</td>
                        <td>{{online_account}}</td>
                    </tr>
                    <tr>
                        <td>IFSC Code No.</td>
                        <td>:</td>
                        <td>{{ifsc_code}}</td>
                    </tr>
                </table>
            </div>
            {% endblock %}
            {% block extracontent %}
            <div id = "declaration">
                I/We here by agree to the terms & conditions as mentioned above.
            </div>
            <div id="declare-sign">
             <br>(Signature of Client/Deptt. Representative)
         </div>
         {% endblock %}        <!-- Dean is liable to change-->
</body>
</html>

src/templates/bills/quoted_success.html
{% extends 'base_register.html' %}
{% load i18n %} {% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
   {% block title %}
   <title>Order added</title>
   {% endblock %}
</head>
<body>
  {% block content %}
  <div class='order-success'>
   <p class='success-message'>Order added <span class='green'>
      Successfully</span></p>
      <table>
       <tr>
          <th>Client:</th>
          <td>{{details.buyer__first_name}}&nbsp;{{details.buyer__last_name}}
           &nbsp;{{details.buyer__customer__title}}</td>
       </tr>
       <tr>
           <th>Address:</th>
           <td>{{details.buyer__customer__address__street_address}}&nbsp;
              {{details.buyer__customer__address__district}}</td>
          </tr>
   </table>
   <div class='order-success-options'>
    <table>
        <tr>
           <th><h3>Options</h3></th>
       </tr>
       <tr>
           <td><a target="_blank" href = '{% url 'prints:quoted_bill' %}?quoted_order_id={{quoted_order_id}}'><input type="button" class="btn btn-info btn-large" name="" value="Proforma Bill"></a></td>
           <tr>
           </table>
       </div>
   </div>
   {% endblock %}
</body>
</html>

src/templates/bills/select_note.html
{% extends "base.html" %} {% load static %}
<html>
<head>
    {% block title %}
    <title>Form</title>
    {% endblock %}
</head>
<body>
    {% block content %}
    <form method="POST" action={% url 'bills:select_note_save' %} >
        {% csrf_token %}
        <table>
            {{form.as_p}}
        </table>
        <input type="submit" class="btn btn-info btn-large" value="Submit">
        <a class = 'add_another' href = ''>
            <input type="button" class="btn btn-info btn-large"
            name="" value="Add Another"></a>
            <a class = 'delete_selected' href = ''>
                <input type="button" class="btn btn-info btn-large btn-danger"
                name="" value="Delete Selected"></a>
    </form>
    {% endblock %}
</body>
</html>